#!/bin/sh

# Include Husky script
. "$(dirname "$0")/_/husky.sh"

# Echo a message indicating the actions being performed
echo '🚀👨🏻‍💻🎉 Initiating the styling, testing, and building of your project before committing...👨🏻‍💻🎉'

# Check Prettier standards
npm run check-format || (
    echo '🎨🚫 Prettier Check Failed! 😱💔.
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run check-lint || (
    echo '🔎🚨 Oh no, ESLint found some issues!😰💥
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false;
)

# Check tsconfig standards
npm run check-types || (
    echo '🤖❌ Oops! Type check failed!😓💡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes, try to build
echo '👌🏻🔨 Code looks good! Initiating build...🤔💪🏻'

npm run build || (
    echo '🏗️😞 Build failed! 😭💔
            Next build failed: View the errors above to see why.
    '
    false;
)

# If everything passes, commit
echo '✅🎉 Everything looks fantastic! You are all set to commit!🥳🎈💚'
